# -*- coding: utf-8 -*-
"""25EE65R13_assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJPr17gx4rHwW2KB-BTVUpwGu0y8O-LP
"""

import torch
import torchvision.transforms as transforms
import torchvision.datasets as datasets
from torch.utils.data import DataLoader
from torch.utils.data import random_split
import matplotlib.pyplot as plt
import numpy as np
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn.metrics import accuracy_score, f1_score,recall_score,precision_score,confusion_matrix

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

"""# Question 1"""

data_set = datasets.EuroSAT(root='./data',transform = None,download=True)

data_set_size=len(data_set)
print(data_set_size)

classes = data_set.classes
print(classes)
print('Total number of classes =',len(classes))

labels=[]
for i,j in data_set:
  labels.append(j)

print(len(labels))
print(labels)

#Dictionary to count the number of classes
def counting(labels):
  count={}
  for i in labels:
    if i in count:
      count[i]+=1
    else:
      count[i]=1
  return count

count_of_lables = counting(labels)
for i in count_of_lables:
  print(classes[i],'=',count_of_lables[i])

"""# Question 2"""

#division of the dataset into train, validation and test sets
#70% Train, 30% Validation, 30% Test
train_data_set, val_data_set, test_data_set = random_split(data_set, [int(0.7 * data_set_size), int(0.15 * data_set_size), int(0.15 * data_set_size)])
print("Length of Train data =",len(train_data_set))
print("Length of Validation data =",len(val_data_set))
print("Length of Test data =",len(test_data_set))

print(data_set[0])
print(data_set[0][0].size)
plt.imshow(data_set[1000][0])

"""The size of the image is 64×64 and it is a coloured image so there will be 3 channels.

# Question 3
"""

#We are performing transformations on the image
train_set_transformations = transforms.Compose([transforms.RandomResizedCrop(64),transforms.RandomHorizontalFlip(),transforms.RandomRotation(20),transforms.ToTensor()])
#In the above line we have resized it as (64*64)
#Made a horizontal Flip and Rotated by 20 degrees
val_set_transformations = transforms.Compose([transforms.RandomResizedCrop(64),transforms.ToTensor()])
test_set_transformations = transforms.Compose([transforms.RandomResizedCrop(64),transforms.ToTensor()])

#Applied the above defined transformations
train_data_set.dataset.transform = train_set_transformations
val_data_set.dataset.transform = val_set_transformations
test_data_set.dataset.transform = test_set_transformations

#LOading the dataset
train_data_loader = DataLoader(train_data_set, batch_size=64, shuffle=True)
val_data_loader = DataLoader(val_data_set, batch_size=64, shuffle=True)
test_data_loader = DataLoader(test_data_set, batch_size=1, shuffle=True)

print(len(train_data_loader))
print(len(val_data_loader))
print(len(test_data_loader))

"""# Question 4"""

#We are defining the Residual block for the CNN
class ResBlock(nn.Module):

  def __init__(self,input_channels,output_channels):
    super(ResBlock,self).__init__()

    self.conv1 = nn.Conv2d(input_channels,output_channels,kernel_size=3,padding=1)
    self.batchnormlayer1 = nn.BatchNorm2d(output_channels)

    self.conv2 = nn.Conv2d(output_channels,output_channels,kernel_size=3,padding=1)
    self.batchnormlayer2 = nn.BatchNorm2d(output_channels)

    #We are using this to tackle the case where no. of inputs are not equal to the no. of outputs
    if input_channels != output_channels:
      self.conv3 = nn.Conv2d(input_channels,output_channels,kernel_size=1,padding=0)
    else:
      self.conv3 = None

  def forward(self,x):
    residual = self.conv3(x)

    output = F.relu(self.batchnormlayer1(self.conv1(x)))

    output = self.batchnormlayer2(self.conv2(output))

    output = F.relu(output + residual)

    return output

#This is our Convolutional Neural Network
class CNNetwork(nn.Module):

  def __init__(self,num_of_classes = len(classes)):

    super().__init__()

    self.conv1 = nn.Conv2d(3,32,3,padding=1)
    self.bn1 = nn.BatchNorm2d(32)

    #Inclusion of the Residual blocks that we have defined earlier
    self.res1 = ResBlock(32,64)
    self.res2 = ResBlock(64,128)

    self.pool = nn.MaxPool2d(2)

    self.gap = nn.AdaptiveAvgPool2d(1)

    self.classifier = nn.Conv2d(128,num_of_classes,1)

  def forward(self,x):
    x = F.relu(self.bn1(self.conv1(x)))
    x = self.pool(x)

    x = self.res1(x)
    x = self.pool(x)

    x = self.res2(x)
    x= self.pool(x)

    x= self.gap(x)

    x = self.classifier(x)

    x = x.view(x.size(0),-1)

    return x

fnl_model = CNNetwork(num_of_classes=len(classes))
fnl_model = fnl_model.to(device)

#we are printing the model summary
print(fnl_model)

"""The appropriate loss function for the classification task is Categorical Cross Entropy loss"""

loss_function = nn.CrossEntropyLoss()
#As mentioned we are gonna use the Adam Optimizer for the learning rate scheduling
optimization_function = optim.Adam(fnl_model.parameters(),lr=0.001)

#We are gonna train the model now
number_of_epochs = 40

training_loss = []
validation_loss = []
fnl_model = fnl_model.to(device)

for epoch in range(number_of_epochs):
  fnl_model.train()
  current_train_loss = 0.0
  for i,j in train_data_loader:
    input, label = i.to(device), j.to(device)
    optimization_function.zero_grad()
    output = fnl_model(input)
    loss = loss_function(output,label)
    loss.backward()
    optimization_function.step()
    current_train_loss += loss.item()
  training_loss.append(current_train_loss/len(train_data_loader))

  fnl_model.eval()
  current_val_loss = 0.0
  with torch.no_grad():
    for i,j in val_data_loader:
      input, label = i.to(device), j.to(device)
      output = fnl_model(input)
      loss = loss_function(output,label)
      current_val_loss += loss.item()

  validation_loss.append(current_val_loss/len(val_data_loader))

  print(f'No of epochs out of {number_of_epochs} are {epoch+1}, Training loss is {(current_train_loss/len(train_data_loader)):.4f}, Validation loss is {(current_val_loss/len(val_data_loader)):.4f}')

#Plotting of Training and Validation loss vs No. of Epochs
plt.plot(training_loss,label='Training loss')
plt.plot(validation_loss,label='Validation loss')
plt.legend()
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and validation loss vs No. of Epochs')
plt.show()

"""# Question 6"""

#We are gonna print the metrics of the model
fnl_model.eval()

predictions=[]
labels=[]

with torch.no_grad():

  for i,j in test_data_loader:

    inputs = i.to(device)
    label = j.to(device)

    output = fnl_model(inputs)

    k,preds = torch.max(output,1)

    predictions.append(preds.cpu().numpy())
    labels.append(label.cpu().numpy())

model_accuracy = accuracy_score(labels,predictions)
model_f1 = f1_score(labels,predictions,average='weighted')

print(f'Model Accuracy ={model_accuracy}\nF1 score ={model_f1}')

model_precision_score = precision_score(labels, predictions,average='weighted')
print("Precision Score =", model_precision_score)
model_recall_score = recall_score(labels, predictions,average='weighted')
print("Recall Score =", model_recall_score)

#Confusion matrix of the model
confusion_mat = confusion_matrix(labels, predictions)
print(confusion_mat)

"""# Question 7"""

#We are gonna implement the Deep Fool attack to our model
#As we are gonna increse the number of iterations and over shoot the attack strength increases
def deep_fool_attack(image,model,num_classes=len(classes),iterations=20,over_shoot=0.03):
  model.eval()
  image = image.clone().detach().to(device)
  image.requires_grad = True

  output = model(image)
  i,label = torch.max(output.data,1)

  perturbations = torch.zeros_like(image).to(device)

  iteration = 0

  while iteration < iterations:

    output = model(image)
    current_label = torch.argmax(output)


    if current_label != label:
      break

    model.zero_grad()
    output[0,current_label].backward(retain_graph=True)
    grad_orig = image.grad.data.clone()

    min_pert = float('inf')

    for k in range(num_classes):

      if k == current_label:
        continue

      image.grad.zero_()

      output[0,k].backward(retain_graph=True)
      grad_k = image.grad.data.clone()

      w_k = grad_k - grad_orig
      f_k = (output[0,k] - output[0, current_label]).data

      pert_k = torch.abs(f_k) / torch.norm(w_k.flatten())

      if pert_k < min_pert:
        min_pert = pert_k
        w = w_k
    r_i = (min_pert * w) / torch.norm(w.flatten())

    perturbations+= r_i

    image = image + (1 + over_shoot) * r_i
    image = image.detach()
    image.requires_grad = True

    iteration += 1

  return image

data_iter = iter(test_data_loader)
images,labels = next(data_iter)
images = images.to(device)
labels = labels.to(device)

adverse_image = deep_fool_attack(images,fnl_model)

original = images.cpu().detach().numpy()[0].transpose(1,2,0)
attacked_image = adverse_image.cpu().detach().numpy()[0].transpose(1,2,0)

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(original)
plt.title('Original Image')

plt.subplot(1,2,2)
plt.imshow(attacked_image, cmap='gray')
plt.title('Adversarial Image')

plt.show()

"""# Question 8"""

#We are gonna see the success rate of the attack
correct_preds =0
mistakes =0

fnl_model.eval()

for input, label in test_data_loader:

  input = input.to(device)
  lable = label.to(device)

  output = fnl_model(input)
  i, preds = torch.max(output, 1)


  if preds.item() == label.item():
    correct_preds +=1

    advers_inputs = deep_fool_attack(input, fnl_model)

    advers_outputs = fnl_model(advers_inputs)
    i,advers_preds = torch.max(advers_outputs,1)

    if advers_preds.item() != label.item():
      mistakes +=1
success_rate = mistakes/correct_preds
print('Correctly classified are =',correct_preds)
print('Successfully attacked =',mistakes)
print('The Deep Fool attack success rate =',success_rate)

#We are going to show the difference the model prediction before and
#after the attack
import numpy as np
import matplotlib.pyplot as plt

fnl_model.eval()

shown = 0

for inputs, labels in test_data_loader:

    inputs = inputs.to(device)
    labels = labels.to(device)

    outputs = fnl_model(inputs)
    i, pred = torch.max(outputs, 1)


    if pred.item() == labels.item():

        adv_inputs = deep_fool_attack(inputs, fnl_model)

        adv_outputs = fnl_model(adv_inputs)
        _, adv_pred = torch.max(adv_outputs, 1)


        if adv_pred.item() != labels.item():

            orig = inputs.cpu().detach().numpy()[0].transpose(1,2,0)
            adv = adv_inputs.cpu().detach().numpy()[0].transpose(1,2,0)

            plt.figure(figsize=(8,4))

            plt.subplot(1,2,1)
            plt.imshow(orig)
            plt.title(f"Original Image\nPredicted as: {pred.item()}")
            plt.axis("off")

            plt.subplot(1,2,2)
            plt.imshow(adv)
            plt.title(f"Adversarial attacked Image\nPredicted as: {adv_pred.item()}")
            plt.axis("off")

            plt.show()

            shown += 1
    #we are using this line because we want to show only 5 images
    if shown == 5:
        break

"""# Question 9"""

!pip install torchattacks

import torchattacks as tt

#this is the inbuilt Deep fool attack function
deep_attack = tt.DeepFool(fnl_model,steps=20,overshoot=0.03)

correct =0
mistakes = 0

fnl_model.eval()

for input, label in test_data_loader:

  input = input.to(device)
  label = label.to(device)

  output = fnl_model(input)
  i,pred = torch.max(output,1)

  if pred.item() == label.item():
    correct +=1

    advers_input = deep_attack(input,label)
    advers_output = fnl_model(advers_input)
    i,advers_pred = torch.max(advers_output,1)

    if advers_pred.item() != label.item():
      mistakes +=1

success_rate = mistakes/correct
print('Correctly classified are =',correct)
print('Successfully attacked =',mistakes)
print('The Deep Fool (torch module) attack success rate =',success_rate)

"""The success rate is almost same as the success arte that we have got during the manual implementation"""